# ------------------------------------------------
# Case Name:
#       case_example_config.yaml
# Case Description:
#       You could add and run any .sh scripts before your ever step.
# Testing Steps:
#       step 1: attempting to cache an entity with an ETag header
#       step 2: verifying whether the cache cached the entity
#       step 3: sending an If-None-Match request where If-Modified-Since is absent 
# Author:
#      buke@alibaba-inc.com
#
# -----------------------------------------------
#
#step 1: attempting to cache an entity with an ETag header
--- {
    Config: {
        sh: "echo 'set the config file before step 1'",
        sh: "echo 'you can also run some .sh scripts here'",
        sh: 'ls -a',
    },
    Request: {
        method: GET,
        uri: '/hktzxguybhrk',
        protocol: HTTP/1.1,
    },
    ServerCheck: {
        method: GET,
        uri: '/hktzxguybhrk',
    },
    Response: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Cache-Control: public,
        Content-Length: 15,
        ETag: "foo",
        Expires: now + 86400,
        Host: "www.mm.cn",
        Last-Modified: now - 86400,
        body: body-pvqmzvmnjw,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-modified: now - 86400,
        Expires: now + 86400,
        ETag: foo,
        content-length: 15,
        body: body-pvqmzvmnjw,
    }
}
#step 2: verifying whether the cache cached the entity
--- {
    Config: {
        sh: "echo 'set the config file before step 2'",
    },
    Request: {
        method: GET,
        uri: '/hktzxguybhrk',
        protocol: HTTP/1.1,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-modified: now - 86400,
        Expires: now + 86400,
        ETag: foo,
        content-length: 15,
        body: body-pvqmzvmnjw,
    }
}
#step 3: sending an If-None-Match request where If-Modified-Since is absent
--- {
    Config: {
        sh: "echo 'set the config file before step 3'",
    }, 
    Request: {
        method: GET,
        uri: '/hktzxguybhrk',
        protocol: HTTP/1.1,
        Host: "www.mm.cn",
        If-None-Match: "bar",
        If-None-Match: "",
        If-None-Match: "foo",
        If-None-Match: "baz",
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-modified: now - 86400,
        Expires: now + 86400,
        ETag: foo,
        content-length: 15,
        body: body-pvqmzvmnjw,
    }
}
